services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    Endroid\QrCodeBundle\Controller\:
#        resource: '../../Controller'
#        tags: ['controller.service_arguments']
#
#    Endroid\QrCode\Builder\BuilderFactoryInterface: '@Endroid\QrCode\Builder\BuilderFactory'
#    Endroid\QrCode\Builder\BuilderFactory: ~

#    Endroid\QrCode\Writer\BinaryWriter: ~
#    Endroid\QrCode\Writer\DebugWriter: ~
#    Endroid\QrCode\Writer\EpsWriter: ~
    Endroid\QrCode\Writer\PngWriter: ~
#    Endroid\QrCode\Writer\SvgWriter: ~
#

    Endroid\QrCode\Builder\QrCodeBuilderInterface: '@Endroid\QrCode\Builder\QrCodeBuilder'
    Endroid\QrCode\Builder\QrCodeBuilder: ~

    Endroid\QrCode\Builder\BuilderInterface: '@Endroid\QrCode\Builder\Builder'
    Endroid\QrCode\Builder\Builder: ~

#
#    Endroid\QrCode\WriterRegistryInterface: '@Endroid\QrCode\WriterRegistry'
#    Endroid\QrCode\WriterRegistry:
#        calls:
#            - [addWriters, [!tagged endroid.qr_code.writer]]
#
#    Endroid\QrCode\Factory\QrCodeFactoryInterface: '@Endroid\QrCode\Factory\QrCodeFactory'
#    Endroid\QrCode\Factory\QrCodeFactory: ~
#
#    Endroid\QrCodeBundle\Twig\QrCodeExtension: ~
#    Endroid\QrCodeBundle\Twig\QrCodeRuntime: ~
