endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        data: 'Life is too short for generating QR codes'
        encoding: 'UTF-8'
        errorCorrectionLevel: high
        #        size: 300
        logoPath: '%kernel.project_dir%/vendor/endroid/qr-code/tests/assets/symfony.png'
        labelText: 'This is the label'
        labelAlignment: center
#        validateResult: true
    custom:
        writer: Endroid\QrCode\Writer\PngWriter
        #        size: 400
        errorCorrectionLevel: low
#        validateResult: false
