endroid_qr_code:
    default:
        data: 'Life is too short for generating QR codes'
        encoding: 'UTF-8'
        errorCorrectionLevel: high
        writerClass: Endroid\QrCode\Writer\PngWriter
        writerOptions:
            size: 300
            roundBlockSizeMode: 'margin'
            validateResult: true
        logoPath: '%kernel.project_dir%/vendor/endroid/qr-code/tests/assets/symfony.png'
        labelText: 'This is the label'
        labelAlignment: center
    custom:
        errorCorrectionLevel: low
        writerClass: Endroid\QrCode\Writer\PngWriter
        writerOptions:
            size: 400
            validateResult: false
